version: '3.1'

services:

  grpc-test:
    image: gusaul/grpcox:latest
    ports:
      - 6969:6969

  mysql:
    build:
      context: ./docker/mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: vgroup
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    volumes:
      - ./mysql:/var/lib/mysql

  consul:
    image: consul
    container_name: consul
    restart: always
    ports:
      - 8500:8500
    environment:
      CONSUL_BIND_INTERFACE: eth0

  # default admin/changeit
  eventstore:
    image: eventstore/eventstore:release-5.0.1
    ports:
      - 2113:2113
      - 1113:1113
    volumes:
      - "~/Data/eventstorenode/node1:/var/lib/eventstore"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:2113/stats || exit 1" ]
      interval: 5s
      timeout: 2s
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=all

  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    command: -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.account_api=enabled
    ports:
      - 8080:8080
    depends_on:
      - mysql
